### ISSUE TITLE
Question: Does device need to get reset?

### ISSUE THREAD

**Issue by keenanjohnson** [goliothlabs/ble_prov_web#1]
This is an excellent example! I have a clarifying question: Does the device need to get reset via a power cycle after these settings are applied or how does that work?

**Comment by ncmiller** [comment]
> Does the device need to get reset via a power cycle after these settings are applied or how does that work?

Yes, you'll need to reset the device for the new settings to take effect. 

Perhaps in a future version, we'll add a BLE "reset" endpoint so this can be done via BLE. But for now, you'll have to reset via button press or UART shell CLI.

**Comment by keenanjohnson** [comment]
Ah got it! Thanks @ncmiller !
